### ISSUE TITLE
Переделать параметры и тип возвращаемого значения в int

### ISSUE THREAD

**Issue by coursar** [pentogono/Monthly-Credit#3]
https://github.com/pentogono/Monthly-Credit/blob/d9d324d8e2c2e1482e9b36cf7fd68bbd94bb19ea/src/main/java/ru/itpark/CreditService.java#L4

При необходимости - конвертируйте в double уже внутри метода.

https://github.com/pentogono/Monthly-Credit/blob/d9d324d8e2c2e1482e9b36cf7fd68bbd94bb19ea/src/main/java/ru/itpark/CreditService.java#L12

**Comment by pentogono** [comment]
@coursar 55069e424217be9219805020135205f318087860
Результат получился очень приближенным, который получается на сайте
