### ISSUE TITLE
Отформатировать код

### ISSUE THREAD

**Issue by coursar** [pentogono/Monthly-Credit#5]
https://github.com/pentogono/Monthly-Credit/blob/d9d324d8e2c2e1482e9b36cf7fd68bbd94bb19ea/src/main/java/ru/itpark/CreditService.java#L6-L10

Ctrl + Alt + L в Windows, Cmd + Alt + L в Mac

**Comment by pentogono** [comment]
@coursar 55069e424217be9219805020135205f318087860
