### ISSUE TITLE
Не выносите в переменные неизменяемые константы вроде 1, 12 месяцев и 100%

### ISSUE THREAD

**Issue by coursar** [pentogono/Monthly-Credit#6]
https://github.com/pentogono/Monthly-Credit/blob/55069e424217be9219805020135205f318087860/src/main/java/ru/itpark/CreditService.java#L6-L8

**Comment by pentogono** [comment]
@coursar а не будет ли это хардкодингом?

**Comment by coursar** [comment]
@pentogono, если жёстко следовать правилам checkstyle - то будет хардкодингом (magic constants), да. Но большинство склоняется к точке зрения, что это допустимо (вероятность того, что количество месяцев в году или 100 процентов изменится - очень низка).

**Comment by pentogono** [comment]
@coursar c428c3f65636cffb8b4e8147d40debfc7af82d39
