### ISSUE TITLE
Зачем два раза приводить к double? Одного раза не достаточно?

### ISSUE THREAD

**Issue by coursar** [pentogono/Monthly-Credit#7]
https://github.com/pentogono/Monthly-Credit/blob/55069e424217be9219805020135205f318087860/src/main/java/ru/itpark/CreditService.java#L9

**Comment by pentogono** [comment]
@coursar 
percentageRate до этого нигде не использовался, поэтому задаем параметр(переменную) и его тип
а  loanRate и hundredPercent приводим к double, т.к. мы вначале задаем их в int

**Comment by coursar** [comment]
если `(double)` оставить только перед loanRate, что изменится?

**Comment by pentogono** [comment]
@coursar ничего не изменилось, запускал под дебагом. Ошибку понял.

**Comment by pentogono** [comment]
@coursar c428c3f65636cffb8b4e8147d40debfc7af82d39
